### ISSUE TITLE
Should replace with context.WithCancel() as it possibly might lead to resource leaks ,as context background never times out

### ISSUE THREAD

**Issue by shubhamdixit863** [numaproj-contrib/aws-sqs-sink-go#8]
https://github.com/numaproj-contrib/aws-sqs-sink-go/blob/7fe2c8a0fe4fb95dbfee35f309bbbdd86b9185eb/main.go#L113

**Comment by chandankumar4** [comment]
Fixed by PR https://github.com/numaproj-contrib/aws-sqs-sink-go/pull/9
